### ISSUE TITLE
Add support to run the pipelines in scratch

### ISSUE THREAD

**Issue by dweemx** [vib-singlecell-nf/vsn-pipelines#195]

**Comment by KrisDavie** [comment]
Not sure I understand this? You can either run the nextflow command in scratch and point the outdir to your wanted folder, or nextflow has an environment variable built in to specify the location of the work directory (NXF_WORK, see: https://www.nextflow.io/docs/latest/config.html#environment-variables).

**Comment by dweemx** [comment]
Didn't know there was a `NXF_WORK`. Otherwise, I was thinking to use the `scratch` directive from Nextflow... Don't know what's easier/best for the use ?

**Comment by KrisDavie** [comment]
`scratch` would also be a way of doing it, but then files need to be copied/linked from the scratch directory to the work directory when nextflow needs them. It would also be an extra burden on people for configuring the pipeline in my opinion. 

It seems like the `scratch` directive is mainly implemented to prevent issues and overhead with writing to NFS mounts, which shouldn't be an issue in the VSC because staging is a GPFS volume. We also don't have a lot of huge I/O processes just a lot of data saved.

**Comment by dweemx** [comment]
@KrisDavie :+1: 
I'm closing it then. 
Use `NXF_WORK` to set the directory where the `work` folder will be saved
