### ISSUE TITLE
[BUG] Cannot run VSN without job submission system

### ISSUE THREAD

**Issue by Ijoanito** [vib-singlecell-nf/vsn-pipelines#321]
Hi @cflerin , 

I am facing a problem to run VSN multi run because I need to submit it as a job. 

Previously, I have get some help from your colleague to fix this problem in arboreto step, but now it again shown similar error in (ADD_PEARSON_CORRELATION) step (as shown in figure below)
![image](https://user-images.githubusercontent.com/52953881/111747068-cf245180-88c9-11eb-92cd-2e034d531f75.png)

Currently I am using AWS system with 96 CPU and 192 GB memory and do not have any SGE system installed on it.

Really appreciate if you can help fixing this problem.

Many thanks in advance.

**Comment by cflerin** [comment]
Hi @Ijoanito ,

Sorry about that, I didn't realize that this exception was included in all of the scenic steps. It should be fixed now if you update your develop branch:
```
nextflow pull vib-singlecell-nf/vsn-pipelines -r develop
```

**Comment by Ijoanito** [comment]
@cflerin thanks! I will try it again.
Another thing, you colleague (Jasper) mentioned that we can choose regulon/target gene that consistently shown in at least 80% (or any number that we want) when we run multirun_scenic. May I know which parameter control this? is it "sc.scenic.aucell.min_regulon_gene_occurrence"?

**Comment by Ijoanito** [comment]
Hi @cflerin ,

Recently I encounter another error related to swap limit in SCENIC_cistarget_motif step. Do you have any suggestion how to resolve this problem?
![image](https://user-images.githubusercontent.com/52953881/112504766-11b4c500-8dc7-11eb-8d88-af5764a156be.png)

Many thanks in advance.

Best,
Joanito

**Comment by cflerin** [comment]
Hi @Ijoanito ,

Sorry that you're still having issues here. In this case are running into the process time limit:
```
Process exceeded running time limit (1d)
```
So, you could try to increase this limit (in the config, you will find an entry `withLabel: 'compute_resources__scenic.*'`). But I see you're already running with 48 threads -- You might be running into a pySCENIC issue where this step appears to stall (if you look in the logs (`work/0d/c96.../.command.log`) you might see that it reaches this 91% fairly early then hangs there for the next ~20 hours). In this case increasing the running time won't help. This _should_ be fixed in the latest pySCENIC release but it's not yet implemented here unfortunately. I would actually suggest to lower your thread count to ~16-20, and restarting the pipeline (with `-resume`), hopefully this will resolve the issue.
